### Get all users 
GET   http://localhost:3000/users

### Get user by username 
GET http://localhost:3000/users/samirfdez

### Register a user
POST  http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Lebron James",
    "username": "KingJames",
    "email": "LebronJ@prueba.com",
    "password": "prueb@123",
    "confirmPassword": "prueb@123"
}

### login user
POST  http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "KingJames",
    "password": "prueb@123"
}
