### Get all users 
GET   http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTY5ZTc0MGM5MDU0MGI4OGQ5NTNjYyIsInVzZXJuYW1lIjoiS2luZ0phbWVzIiwiaWF0IjoxNzIxMjQ2MDYwLCJleHAiOjE3MjEyNDk2NjB9.gMAI14g8CnR7qMoOQQoqMyjRkXOR0LxGZP-h88MuaRo

### Get user by username 
GET http://localhost:3000/users/KingJames
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTY5ZTc0MGM5MDU0MGI4OGQ5NTNjYyIsInVzZXJuYW1lIjoiS2luZ0phbWVzIiwiaWF0IjoxNzIxMjQ2MDYwLCJleHAiOjE3MjEyNDk2NjB9.gMAI14g8CnR7qMoOQQoqMyjRkXOR0LxGZP-h88MuaRo


### Register a user
POST  http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "Lebron James",
    "username": "KingJames",
    "email": "LebronJ@prueba",
    "password": "prueb@123",
    "confirmPassword": "prueb@123"
}

### login user
POST  http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "KingJames",
    "password": "prueb@123"
}

